export const FETCH_DRINKS = 'FETCH_DRINKS';
export const FETCH_DRINKS_PENDING = 'FETCH_DRINKS_PENDING';
export const FETCH_DRINKS_ERROR = 'FETCH_DRINKS_ERROR';
export const DRINK_SELECTED = 'DRINK_SELECTED';