export const FULLNAME_INPUT_CHANGE = 'FULLNAME_INPUT_CHANGE';
export const EMAIL_INPUT_CHANGE = 'EMAIL_INPUT_CHANGE';
export const PHONE_INPUT_CHANGE = 'PHONE_INPUT_CHANGE';
export const ADDRESS_INPUT_CHANGE = 'ADDRESS_INPUT_CHANGE';
export const VOUCHER_INPUT_CHANGE = 'VOUCHER_INPUT_CHANGE';
export const MESSAGE_INPUT_CHANGE = 'MESSAGE_INPUT_CHANGE';